
UPDATE IDS T1
SET NEXT_ID = '1' 
WHERE T1.TABLE_NAME = 'FILE_ID';

UPDATE IDS T1
SET NEXT_ID = '1' 
WHERE T1.TABLE_NAME = 'BOARD_ID';

SELECT T1.FILE_ID, 
       T1.FILE_SN, 
       T1.FILE_PATH, 
       T1.FILE_UPLOAD_NM, 
       T1.FILE_ORIGIN_NM, 
       T1.FILE_EXT, 
       T1.FILE_SIZE 
FROM FILE_DETAIL T1 
WHERE T1.FILE_ID = 'FILE_000000000000021'
AND T1.FILE_SN = '0';
 
SELECT * 
FROM FILE_MASTER T1 INNER JOIN FILE_DETAIL T2 ON T1.FILE_ID = T2.FILE_ID
WHERE T1.FILE_ID = 'FILE_000000000000015'
ORDER BY T2.FILE_SN;


