CREATE TABLE BOARD (
  BOARD_ID     		  CHAR(20 BYTE)          NOT NULL, 
  TITLE      		  VARCHAR2(200 BYTE)         NULL, 
  CONTENT    		  CLOB                       NULL, 
  REG_DATE   		  DATE                       NULL, 
  HIT_COUNT  		  NUMBER                     NULL, 
  FILE_ID      CHAR(20 BYTE)        		 NULL
);

ALTER TABLE BOARD ADD
(
    CONSTRAINT PK_BOARD
    PRIMARY KEY ( BOARD_ID )
);

CREATE TABLE QBIC.USERS (
  ID        VARCHAR2(10 BYTE)     NOT NULL, 
  PASSWD    VARCHAR2(10 BYTE)         NULL
);

ALTER TABLE QBIC.USERS ADD
(
    CONSTRAINT PK_USERS
    PRIMARY KEY ( ID )
);

CREATE TABLE IDS (
  TABLE_NAME    VARCHAR2(20)     NOT NULL,
  NEXT_ID       NUMBER(30)      DEFAULT 0       NOT NULL
)
;

CREATE TABLE QBIC.FILES (
  FILE_ID           CHAR(20 BYTE)          NOT NULL, 
  FILE_PATH         VARCHAR2(256 BYTE)         NULL, 
  FILE_UPLOAD_NM    VARCHAR2(256 BYTE)         NULL, 
  FILE_ORIGIN_NM    VARCHAR2(256 BYTE)         NULL
);

ALTER TABLE QBIC.FILES ADD
(
    CONSTRAINT PK_FILES
    PRIMARY KEY ( FILE_ID )
);


ALTER TABLE IDS ADD
(
    CONSTRAINT IDS_PK
    PRIMARY KEY ( TABLE_NAME )
);

insert into IDS(TABLE_NAME,NEXT_ID) values ('FILE_ID',1);
insert into IDS(TABLE_NAME,NEXT_ID) values ('BOARD_ID',1);
